// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbVPr2OeIMgTID3fRDl-nofRAZvjeXTss',
    appId: '1:418277499572:web:728f7bac46739bb6926de1',
    messagingSenderId: '418277499572',
    projectId: 'samplestorage-7f3e6',
    authDomain: 'samplestorage-7f3e6.firebaseapp.com',
    storageBucket: 'samplestorage-7f3e6.appspot.com',
    measurementId: 'G-53RX253C8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF8m7bHa86TbRZqD2LQtFrO_d3_Xylb7o',
    appId: '1:376109847141:android:a394085dab75fe86d16c8c',
    messagingSenderId: '376109847141',
    projectId: 'bfdbf-f9932',
    storageBucket: 'bfdbf-f9932.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTJpWaXeqeDpDf-hrbh_et82jBEAgqBAM',
    appId: '1:376109847141:ios:167a45b7774e8fc2d16c8c',
    messagingSenderId: '376109847141',
    projectId: 'bfdbf-f9932',
    storageBucket: 'bfdbf-f9932.appspot.com',
    iosBundleId: 'com.example.cushion1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxneOukqYZr0TOHCTfLU5Ofw_VJ_HX9JI',
    appId: '1:650177460260:ios:2d6b5f1ee6e0fb434e40b1',
    messagingSenderId: '650177460260',
    projectId: 'positiontimes',
    storageBucket: 'positiontimes.appspot.com',
    iosBundleId: 'com.example.cushion1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbVPr2OeIMgTID3fRDl-nofRAZvjeXTss',
    appId: '1:418277499572:web:e9003b4ae8b7099c926de1',
    messagingSenderId: '418277499572',
    projectId: 'samplestorage-7f3e6',
    authDomain: 'samplestorage-7f3e6.firebaseapp.com',
    storageBucket: 'samplestorage-7f3e6.appspot.com',
    measurementId: 'G-9G4VM2QFR5',
  );

}